#pragma once

//
// Control flow interruption events.
//
typedef enum _AML_INTERRUPTION_EVENT {
    AML_INTERRUPTION_EVENT_NONE,
    AML_INTERRUPTION_EVENT_CONTINUE,
    AML_INTERRUPTION_EVENT_BREAK,
    AML_INTERRUPTION_EVENT_RETURN
} AML_INTERRUPTION_EVENT;

//
// Evaluation pass type.
//
typedef enum _AML_PASS_TYPE {
    AML_PASS_TYPE_NAMESPACE,
    AML_PASS_TYPE_FULL,
} AML_PASS_TYPE;