name: CI
on: [push, pull_request]

jobs:
  clang-ci:
    runs-on: ${{ matrix.os }}
  
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest]
        
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: setup tools
        uses: actions/setup-python@v5
      
      - name: meson build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build

      - name: Check if DSDT.aml exists
        run: ls -l tests/feature_test_1
        working-directory: ${{ github.workspace }}
          
      - name: meson test
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test

      - name: upload meson test logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: meson_test_log${{ matrix.os }}.txt
          path: build/meson-logs/testlog.txt
